name: Validate build

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    container:
      image: docker.pkg.github.com/painhardcore/builder/builder:latest
      credentials:
       username: ${{ github.actor }}
       password: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Compile proto files
      run:  make compile-proto
      
    - name: Generate CRD
      run:  make generate-deepcopy
      
    - name: Get dependencies
      run:  make dependency
      
    - name: Build
      run: make build
