name: Validate commit

on: [push, pull_request]

jobs:

  build:
    name: Build && test
    runs-on: ubuntu-18.04
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - uses: helm/kind-action@v1.1.0
    - name: Testing
      run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
          
    - name: Prepare Golang 
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15.3'

    - name: install golangci-lint
      run: |
        wget -O golangci-lint.deb https://github.com/golangci/golangci-lint/releases/download/v1.36.0/golangci-lint-1.36.0-linux-amd64.deb
        sudo dpkg -i golangci-lint.deb
         
    - name: Compile proto files
      run: make install-compile-proto

    - name: Generate CRD
      run: |
        make install-controller-gen
        make generate-deepcopy
        
    - name: Get dependencies
      run:  make dependency

    - name: Lint
      run: |
        GOGC=300 make lint
        make lint-charts
          
    - name: test
      run: CI=false make test

    - name: test sanity
      run: |
        helm install baremetal-csi-plugin ./charts/baremetal-csi-plugin
        helm install scheduler-extender ./charts/scheduler-extender
        helm install csibm-operator ./charts/csibm-operator
        make test-sanity
        
        
    - name: Build
      run: make build
