name: Validate commit

on: [push, pull_request]

jobs:

  build:
    name: Build && test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Prepare Golang 
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15.3'

    - name: install golangci-lint
      run: |
        wget -O golangci-lint.deb https://github.com/golangci/golangci-lint/releases/download/v1.36.0/golangci-lint-1.36.0-linux-amd64.deb
        sudo dpkg -i golangci-lint.deb
         
    - name: Compile proto files
      run: make install-compile-proto

    - name: Generate CRD
      run: |
        make install-controller-gen
        make generate-deepcopy
        
    - name: Get dependencies
      run:  make dependency

    - name: Lint
      run: |
        GOGC=200 make lint
        make lint-charts

    - name: test
      run: CI=false make test

    - name: Build
      run: make build
